Remove wget warning, since wget is no longer used
mahrtayyab/tweety pull request #22
Opened 2023-05-07 08:43 UTC by dgw

Module still printed warning about wget not being installed at import time, despite no longer using wget for anything.

2023-05-08 17:06 UTC, mahrtayyab requested changes
It looks like the WORKBOOK_HEADERS which are **required** are begin effected in this PR too , you are welcome to submit another PR without removing 'WORKBOOK_HEADERS'

2023-05-08 18:02 UTC, dgw commented
Ah, sorry about that. That's what happens when I create PRs at 3am. Will fix when I get home tonight!

2023-05-09 07:21 UTC, dgw commented
Got home much (_much_) later than expected, but I have restored the `WORKBOOK_HEADERS`

2023-05-10 04:49 UTC, mahrtayyab approved these changes

2023-05-10 04:49 UTC, merged